### ISSUE TITLE
include web sockets demo on pushing an input's value on change event

### ISSUE THREAD

**Issue by mikedevita** [nneves/Raspberrypi_GPIO#3]
I have a two pole switch (on/off) that im trying to dynamically update without polling via a REST api. It'd be great to have web sockets pub to a channel when a specific GPIO value changes from 0 to 1.

**Comment by nneves** [comment]
When launching with the websockets options active it already broadcasts the GPIO changes over all clients (will not broadcast to the client of the "command origin") for UI update (fixed in issue #2), but probably you would require something more 'explicit', having a specific broadcast channel for each GPIO to receive ON/OFF updates? 
Should I also send notifications to the client that made the original request? Maybe I should, that option is off in the previous patch because the UI already updates itself and the internal variable.

I'm a bit busy at the moment with non-opensource related work, but I can look into this next week and add such demo code into the current UI, think that this may be useful.

**Comment by mikedevita** [comment]
yeah im getting an error when i enable web sockets saying it cant run as headers are already being sent or something like that.

**Comment by mikedevita** [comment]
### The concept works like this.

I am creating a nodeJs based GPIO interface for my garage door. The Garage door will have two magnetic switches, one at the floor and one at the backstop of the garage door rail. The purpose of these switches is to determine to position of the garage door and provide contextual feedback.

These switches will each be on a GPIO input.

### I also have several outputs:
- LED for switches to indicate door is opening, LED will be on (or flashing eventually) when both switches are in OPEN state.
- LED for alert that someone is on the websockets channel
- Relay1 of my relay board which ties in to the wall garage door switch to trigger it in a 101 sequence with a 400ms delay between.

### How it works:

When the garage door page is loaded it ideally should sub to a channel and get the initial state of the door (open/closed). When the button is pressed, Relay1 is triggered and floor switch goes into OPEN state as the door opens, LED clicks on and nodeJs pubs to the channel showing door is opening. Webpage will update with information showing door is opening. Ceiling switch then will go into CLOSED state when doors full open and pubs to the channel showing door is opened. Webpage will update with information showing door is opened. LED light will turn off once Ceiling switch goes into CLOSED state.

Obviously this concept is a lot more specific than what you need to provide. **I think a basic pub/sub model of your script would be sufficient** onChange of single GPIO update a defined channel with data.

I currently have a concept of this working using long polling via an ajax loop but this is not the ideal solution obviously.

**Comment by nneves** [comment]
Regarding "error when i enable web sockets saying it cant run as headers are already being sent", not really sure, need to test it (I have an idea of something that I've fixed in my other webapp), if you could replicate this and open another issue just for this error ...

Thanks for your detailed info for you project, I haven't tested my code using GPIO in INPUT mode, but imagine that should not be a problem and should work fine, as in for the Pub/Sub mode, webscokets functionality already works pretty well and covers all needs, I will make an example on my source code on how to register a specific event for the GPIO ON/OFF broadcast (will cover input/output mode). 

Again, will only be able to make something next week (will be travelling this night and back on Monday - restrict access to mail)

**Comment by mikedevita** [comment]
Yeah this is no rush kind of thing, if i come up with something before then ill make sure to contribute and update. Ill create a seperate issue about the headers already being sent error.

**Comment by dsteinel** [comment]
hey there,
first of all, thanks for the nice project! It works fine for me (without websockets). 

Is there any solution about the headers already being sent error? I get the same error as mike when I try to run it with websockets ...

**Comment by nneves** [comment]
Hey guys,

first of all I apologise @mikedevita for the lack of the promised demo ...

@dsteinel , I've been trying this out on my oldie rPi running node v0.8.10 and I'm unable to replicate the "headers are already being sent", it does sound familiar but I can't seem to track down this in my other project ...

From the top of my head, my current rPi is not responding to the hostname (must have broken something in the way),  so I have my Chrome Browser pointing directly to the rPi IP address:port (http://192.168.1.150:8080), and using REST or websockets it works fine ... I even checked if the resource for the socket.io was being set correctly (http://192.168.1.150:8080/socket.io/socket.io.js), in the REST mode it will send a dummy comment, just to avoid error on the index.html script loading.

Can you please check if you still get that error when using the IP address instead of the hostname (for the websocket mode)?

ps: I've updated the README.md image links, github must have changed something in the way ...

**Comment by dsteinel** [comment]
hey,
thanks alot for the help! 
I have now updated the nodejs version to the newest stable v0.10.20 and I still get the websocket problem after a few seconds. Thing is that the "headers already being sent error" comes up after I launch it in the browser (I am pointing directly to the rPi via address:port).

Is it possible that I have to downgrade to the older node v0.8.10 version?
greetings

**Comment by dsteinel** [comment]
okay, right now i could kill myself ... literally ... 
I seems that i did not install socket.io correctly. After installing the socket.io package everything works fine now! Now error, and the websocket runs perfectly!

I am sorry for beeing such a _..._ . Thanks for the help and thanks for the nice project!!

**Comment by nneves** [comment]
I just wondering about some possible issues between Node.js v0.10.20 and old socket.io dependencies ... I'm really happy that you manage to get this ironed out! Never mind for being such a ... I assure you that you have been really helpful!!! Thanks for using this, feel free to explore and make suggestions (pull requests are very welcome), as you guys can see I haven't touched this in a while (my boss is killing me with piles of work), so expect some long time response (but feel free to ping me from time to time).

**Comment by nneves** [comment]
PS: if you feel brave and want to test this with the latest npm packages under the node.js v0.10.20 just go into the package,json file and replace fixed dependency revision:

// currently

```
  "dependencies": {
    "union": "0.3.0",
    "flatiron": "0.2.8",
    "ecstatic": "0.1.6",
    "rpi-gpio": "0.0.3",
    "socket.io": "0.9.10"
  }
```

// replace with

```
  "dependencies": {
    "union": "*",
    "flatiron": "*",
    "ecstatic": "*",
    "rpi-gpio": "*",
    "socket.io": "*"
  }
```

Haven't tracked down things that may have changed, neither tested this!!! 
Oh, and use `npm update` instead of `npm install` to get your new packages updated!

**Comment by dsteinel** [comment]
Thanks for that. I replaced it and it works fine.
I am glad that I didn't bother you...

greetings
Timmi

Am 11.10.13 11:30, schrieb Nelson Neves:

**Comment by nneves** [comment]
Closing this issue, no time available to fix old projects!
